<a href="https://colab.research.google.com/github/2019130806/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [14]:
def phasor(amp,sr,dur,freq):
  t=np.arange(1,sr*dur+1)/sr
  theta=t*2*np.pi*freq
  s=np.sin(theta)
  return s, theta, t

In [15]:
phasor (1,10000,0.5,100)

(array([ 6.27905195e-02,  1.25333234e-01,  1.87381315e-01, ...,
        -1.25333234e-01, -6.27905195e-02,  1.96438672e-15]),
 array([6.28318531e-02, 1.25663706e-01, 1.88495559e-01, ...,
        3.14033602e+02, 3.14096434e+02, 3.14159265e+02]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 4.998e-01, 4.999e-01,
        5.000e-01]))